"""took out duration

Revision ID: 7cccff8124b5
Revises: d923187e1f69
Create Date: 2021-10-24 18:13:17.706042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cccff8124b5'
down_revision = 'd923187e1f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
