"""changed relationship for show and genre

Revision ID: 09e032dab8f2
Revises: 7cccff8124b5
Create Date: 2022-01-10 22:10:57.350984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e032dab8f2'
down_revision = '7cccff8124b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_genres',
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='show_genres_genre_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name='show_genres_show_id_fkey'),
    sa.PrimaryKeyConstraint('show_id', 'genre_id', name='show_genres_pkey')
    )
    # ### end Alembic commands ###
